#ifndef __INTERNAL_GTK_PRIVATE_H__
#define __INTERNAL_GTK_PRIVATE_H__

#include <gtk/gtkwidget.h>

G_BEGIN_DECLS


#define GTK_PARAM_READABLE G_PARAM_READABLE|G_PARAM_STATIC_NAME|G_PARAM_STATIC_NICK|G_PARAM_STATIC_BLURB
#define GTK_PARAM_WRITABLE G_PARAM_WRITABLE|G_PARAM_STATIC_NAME|G_PARAM_STATIC_NICK|G_PARAM_STATIC_BLURB
#define GTK_PARAM_READWRITE G_PARAM_READWRITE|G_PARAM_STATIC_NAME|G_PARAM_STATIC_NICK|G_PARAM_STATIC_BLURB

G_END_DECLS

#endif /* __INTERNAL_GTK_PRIVATE_H__ */
